---
- hosts: all
  gather_facts: no
  remote_user: ubuntu
  become: yes
  become_user: root
  
  tasks:
  - name: Create file in specific path
    copy:
      content: "{{ input_text }}"
      dest: "{{ file_path }}"