---
- hosts: all
  gather_facts: no
  remote_user: ubuntu
  become: yes
  become_user: root
  
  tasks:
    - name: Run get_appconfig_data script
      shell: |
        APPLICATION_ID="{{ application_id }}" ENVIRONMENT_ID="{{ environment_id }}" CONFIG_PROFILE_ID="{{ config_profile_id }}" FILE_PATH="{{ file_path }}" FILE_TYPE="{{ file_type }}" python3 /opt/goorm/scripts/get_appconfig_data/main.py
        cat "{{ file_path }}"
      register: result
  
    - name: Print result variable
      debug:
        msg:
          - "{{ result.stdout | from_json }}"

    
